.github/CODEOWNERS, .github/FUNDING.yml
Thanks for this most awesome project! Perhaps these files would make sponsoring you more straigthforward 🚀.
=> Add GitHub data for funding and code owners

resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter.clj
state should be seen as an atom, I forget about this in the first pr :(
=> fix flutter clj-kondo hook: state value is atom

resources/clj-kondo.exports/tensegritics/clojuredart/config.edn, resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter.clj
- Update to new rules with dispose.
- Fix bug with not allowing :ticker and :with without a state.
- Use custom linter now to avoid the problem of being completely broken on any problem (now most of the time shows only the one main problem).
=> fix widget hook, use custom linter

doc/differences.md
=> add record creation docs

resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter.clj
Add first support. Video to look how it works https://twitter.com/ArturDumchev/status/1524490073848401927?s=20&t=UJ0TeXto86CzRTiBw59aCQ
I will take a look how to support :inherit names renaming
=> support widget-macro keys:inherit, bind, nested-in

doc/flutter-quick-start.md
Add documentation for Android emulation
=> [doc] flutter-quick-start

samples/gridlist/deps.edn, samples/gridlist/src/sample/gridlist.cljd
=> Samples : GridLists

samples/tabs/deps.edn, samples/tabs/src/samples/tabs.cljd
=> Add tabs sample

samples/datatable/deps.edn, samples/datatable/src/sample/datatable.cljd
=> Add datatable sample

samples/hero_animations/deps.edn, samples/hero_animations/src/sample/hero_animations.cljd
https://docs.flutter.dev/cookbook/navigation/hero-animations
=> hero animations sample

samples/gesture_detector/deps.edn, samples/gesture_detector/src/sample/gesture_detector.cljd
https://user-images.githubusercontent.com/59285665/175553949-77acb507-0e7c-438c-974c-1b8b2029b15a.mov
=> Sample gesture detector

.gitignore, clj/src/cljd/core.cljd, clj/src/cljd/flutter/alpha.cljd, run-tests, samples/.gitignore, samples/animated_container/src/sample/animated_container.cljd, samples/counter/src/sample/counter.cljd, samples/datatable/src/sample/datatable.cljd, samples/drawer/src/sample/drawer.cljd, samples/fab/src/sample/fab.cljd, samples/fade_widget/src/sample/fade_widget.cljd, samples/form_handle_change_textfield/src/sample/form.cljd, samples/form_retrieve_input/src/sample/form.cljd, samples/gesture_detector/src/sample/gesture_detector.cljd, samples/gridlist/src/sample/gridlist.cljd, samples/hero_animations/src/sample/hero_animations.cljd, samples/navigation/src/sample/navigation.cljd, samples/physics_simulation/src/sample/physics_sim.cljd, samples/snackbar/deps.edn, samples/snackbar/src/sample/snackbar.cljd, samples/tabs/src/sample/tabs.cljd, samples/twocounters/src/sample/two_counters.cljd
- Few changes to core.cljd and alpha.cljd
- Updated samples
- Light reformatting (left alignments)
Tested by running `run-tests` and the samples.
I didn't try to change things proactively, as I am unsure about test coverage. Instead I only changed issues surfaced by running tests.
=> new param/property syntax everywhere

clj/src/cljd/zip.cljc, clj/test/cljd/test_clojure/clojure_zip.cljd, run-tests
second try after #151.
only [s/clojure.zip/cljd.zip/](https://github.com/Tensegritics/ClojureDart/commit/2171b169baba7fa872a9c20e1877b0d18d918a7b) ❤️
=> Port 'clojure.zip' #2

clj/src/cljd/walk.cljd, clj/test/cljd/test_clojure/clojure_walk.cljd, run-tests
=> Ported `cljd.test-clojure.clojure-walk`

clj/src/cljd/core.cljd, clj/test/cljd/test_clojure/other_functions.cljd, run-tests
- copied updated-vals, update-keys from core.clj
- copied test clojure.test-clojure.other-functions
- commented out test-some-fn
- commented out test-regex-matcher
- commented out part of test-update-{vals,keys} that uses array-map, sorted-map
=> add update-vals, update-keys from clojure 1.11

clj/src/cljd/build.clj, clj/src/cljd/compiler.cljc, resources/analyzer.dart
Refactoring types so that members are kept separated from types themselves to:
* stop having humongous data structures for types
* paving the path for @dupuchba new analyzer integration
=> Beginning the great members migration!

clj/src/cljd/build.clj, clj/src/cljd/compiler.cljc, clj/src/cljd/core.cljd
Working hot reload, still has some bugs with defonce
#161
=> Hotreload friendly compiler

resources/analyzer.dart
should fix #10 once merged
TODO:
- don't lift extensions
- support type parameters propagation
=> WIP extension implem

samples/README.md, samples/form_validate/deps.edn, samples/form_validate/src/sample/form.cljd
I added a port of the 'Build a form with validation' [cookbook](https://docs.flutter.dev/cookbook/forms/validation).
=> Adding sample cookbook for form validation

samples/video_player/README.md, samples/video_player/deps.edn, samples/video_player/src/sample/video_player.cljd
Adding example for flutter's video_player plugin
=> Adding example for flutter's video_player plugin

resources/clj-kondo.exports/tensegritics/clojuredart/config.edn
Fixing https://github.com/Tensegritics/ClojureDart/issues/221
=> Support bool type

resources/clj-kondo.exports/tensegritics/clojuredart/config.edn, resources/clj-kondo.exports/tensegritics/clojuredart/hooks/cljd_core.clj
Fixes https://github.com/clj-kondo/clj-kondo/issues/2230
=> Add lint support for stacktraces in catch

doc/README.md
Added an outline, as I would be otherwise scrolling through the docs all day.
Fixed some typos on the way and changed some words to improve readability (hopefully)
=> Outline, typos, wording

clj/src/cljd/core.cljd
Fix dynamic warning issue #326.
=> Fix abs Dynamic Warning

clj/src/cljd/core.cljd, clj/src/cljd/math.cljd, clj/test/cljd/test_clojure/math.cljd, clj/test/cljd/test_clojure/numbers.cljd, clj/test/cljd/test_clojure/predicates.cljd, run-tests
- Adds port of `clojure.math` as `cljd.math`
- Adds `cljd.core` functions:
- `unsigned-bit-shift-right`
- `NaN?`
- `infinite?`
`test-clojure.numbers` and `test-clojure.predicates` tests are also included for testing `unsigned-bit-shift-right` and `NaN?` / `infinite?` core functions, respectively.
=> Create cljd.math namespace
