clj/src/cljd/flutter/alpha.cljd

The order in the generated macro is incorrect: 
```clojure
(widgets/Builder.
:key
("key-name" foundation/ValueKey.)
:builder
....
```
from:
```clojure
(macroexpand 
'(widget
:context ctx
:key "key-name" ....
```
Quick demo:

fix widget-macro's key creation

---

resources/clj-kondo.exports/tensegritics/clojuredart/config.edn

until it will be fix https://github.com/Tensegritics/ClojureDart/issues/27 <p>
discussed in [slack](https://clojurians.slack.com/archives/C03A6GE8D32/p1650367945037689)

omit Non-arg vec return type hint linter

---

clj/src/cljd/flutter/alpha.cljd
resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter.clj

- use :ticker name and :tickers names as let bindings
- use :with and :with->:let names as let bindings
- :with allowed only with state
- :ticker allowed only with state
- :tickers allowed only with state
- can't use both :ticker and :tickers
- :with top names should be simple bindings
- :with let could be not simple - allow destructuring
where state = (or state watch)
[Slack thread](https://clojurians.slack.com/archives/C03A6GE8D32/p1650715334226749?thread_ts=1650669838.842329&cid=C03A6GE8D32)

update clj-kondo widget hook (:with :ticker)

---

README.md
doc/MUNGING.md
doc/differences.md
doc/flutter-helpers.md
doc/quick-start.md

Fixing a few typos I've noticed while reading the docs. Not sure if `string typing` (instead of `strong typing`) was intentional - it can work both ways. I'll revert that bit from the PR if it was.

Fix doc typos

---

README.md
doc/flutter-quick-start.md

Skipping the colon is not supported in Clojure's cli
Conversation in [slack](https://clojurians.slack.com/archives/C6QH853H8/p1655410531905709)

Add semicolons to M cli examples

---

clj/src/cljd/reader.cljd

`if test` are `(satisfies? cljd.core/IWithMeata obj)`.
So maybe message should be using word `IWithMeta`.

typo - s/IMetas/IWithMeta/

---

resources/clj-kondo.exports/tensegritics/clojuredart/config.edn
resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter2.clj

Fix https://github.com/Tensegritics/ClojureDart/issues/191
Add directive support for:
:bg-watcher :let :managed :watch :vsync :context :get
Not fully supported:
1. `:bg-watcher` is just ignored.
2. Keys in a first place, like `:dispose` or `:refresh-on` in some binding forms are just ignored.
Not supported:
`:flds` destructuring. I will consider making a PR into clj-kondo, I have a [commit](https://github.com/D00mch/clj-kondo/commit/26b5901b68d5897d9fcd888350913da8b8c2e9c2) in my local branch already

Add cljd.flutter.alpha2/widget clj-kondo support

---

clj/src/cljd/test.cljd
clj/test/cljd/test_clojure/test_test.cljd
run-tests

Fixes #242 
In clojure.test they're at the namespace level so I decided to match to that. In cljd (dart) they could be at the test group level (though I don't know if cljd.test translates `testing`s to dart test `group`s). However they can't be included in the `thunk#` that is given to `dt/test`--this results in a `Can't call setUp() once tests have begun running` error. 
It wasn't clear to me at first what "resources" are passed in to the unary fixture, so I added an explanation line to the docstring. I also tweaked a location that referred to the clojure.test way of writing a fixture--in cljd.test they have to be a 0-ary and a unary from what I see. (The clojure.test way `(fn [f] ,,, (f) ,,,)` resulted in a NoSuchMethodError: Closure call with mismatched arguments.)

Fix `use-fixtures :each` behavior

---

clj/src/cljd/core.cljd

I'm looking at providing some initial support for ClojureDart in [Portal](https://github.com/djblue/portal/pull/193) and people typically use it via `add-tap` / `remove-tap`. I took the ClojureScript implementation and got it working in dart.

Port add-tap / remove-tap from ClojureScript

---

samples/README.md

Without `init` compilation fails

Fix samples doc: add missing `init` command

---

clj/src/cljd/build.clj

Aliases the behavior of -h/--help.
Resolves #267 
I didn't realize -h/--help existed so hopefully this `help`s.

Add "help" as a cljd command

---

resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter2.clj

Adds support for the following
- `:managed`
- `:watch`
- `:bg-watcher`

Add linter support for widget's options

---

resources/clj-kondo.exports/tensegritics/clojuredart/config.edn

Updated the list of implicit imports from [ns-prototype](https://github.com/Tensegritics/ClojureDart/blob/8da5840981f17111fbb4442239a12c3605b9297c/clj/src/cljd/compiler.cljc#L279-L349)
Probably resolves https://github.com/clj-kondo/clj-kondo/issues/2229 and https://github.com/clj-kondo/clj-kondo/issues/2231

Add lint support for dynamic and other dart:core types

---

clj/src/cljd/compiler.cljc

If the type of the result of the test expression has overridden the == operator with a type in the signature, a TypeException can be thrown. This change ensures we use the == operator implementation of the false/nil objects, which will not throw an exception.

Reorder test expression with false/null.

---

clj/src/cljd/build.clj

`cljd compile` and `cljd test` exit with code 0 (success) if compilation fails
In case compilation was unsuccessful, `System/exit 1`

Exit with error code if compilation unsuccessful

---

samples/fizzbuzz/src/sample/fizzbuzz.cljd

- The app displayed a null error message during the first second after startup. Providing :default values to the :watch directives fixed this.
- :sub/opts map deleted because my understanding is that this functionality was removed when cljd.flutter came out of alpha status
- (on Linux with a font size of 64) the number was rendered 1 or 2 pixels higher when "Fizz" and/or "Buzz"  is rendered. Using a single space instead of an empty string as the placeholders fixes this.

[sample.fizzbuzz] Fix null error and work around rendering bug

---

resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter2.clj

The current rewrite hook doesn't include the (hidden) context argument.
```clj
(def foo
(f/build
[_]
m/Container))
(foo ctx 42)
```
>error: user/foo is called with 2 args but expects 1
Passes lint
Prepend `_ctx` to the rewritten build argsvec

Fix linter for f/build

---

clj/src/cljd/core.cljd
clj/test/cljd/test_clojure/core_test.cljd
clj/test/cljd/test_clojure/core_test_cljd.cljd

Inspired by similar issues found in Clojure:
https://frenchy64.github.io/fully-satisfies/latest/io.github.frenchy64.fully-satisfies.uniform.html

Add missing sentinels to partition-by, dedupe, halt-when

---

clj/src/cljd/core.cljd
clj/test/cljd/test_clojure/core_test_cljd.cljd

This ports the following patch:
https://github.com/clojure/clojure/commit/42d713929e8f7ecd77efe23384238d29bde62aba

CLJ-2649: Fix 3-arg some-fn and every-pred

---

clj/src/cljd/core.cljd
clj/test/cljd/test_clojure/parse.cljd
run-tests

Add `time`, `parse-long`, `parse-double` and `parse-boolean` functions.

Add missing clojure.core functions

---

resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter2.clj

Support for `:when` in clj-kondo. Also :visible looks to be not supported so I deleted it.
This showed warning. (unused-binding)
```clojure
(def pred (atom true))
(f/widget
:watch [pred? @pred]
:when pred?
...)
```

`:when` support by clj-kondo

---

resources/clj-kondo.exports/tensegritics/clojuredart/hooks/flutter2.clj

This provides basic linter support for user-defined directives which includes marking any bindings passed to them as used and ensuring the symbol that the qualified keyword resolves to is defined.
Examples...
```clj
(ns sample.main
(:require
["package:flutter/material.dart" :as m]
[cljd.flutter :as f]
[sample.directives :as directives]))
(defn inline-directive [count .child]
(f/widget
:bind {:foo count}
child))
(defn my-widget []
(f/widget
:get {navigator m/Navigator}
;; warns that this function does not exist
::directives/with-something-else {}
;; navigator is marked as being used
::directives/with-dispatch {:navigator navigator}
;; ::inline-directive seems to resolve to clojure.core/inline-directive,
;; not sure if I can support that form
:sample.main/inline-directive 42
...))
``` …

Provide linter support for user-defined widget directives.

---

clj/src/cljd/core.cljd
clj/src/cljd/edn.cljd
clj/src/cljd/math.cljd
clj/src/cljd/test.cljd
clj/test/cljd/test_clojure/clojure_walk.cljd
clj/test/cljd/test_clojure/core_test.cljd
clj/test/cljd/test_clojure/core_test_cljd.cljd
clj/test/cljd/test_clojure/edn_test.cljd
clj/test/cljd/test_clojure/numbers.cljd
clj/test/cljd/test_clojure/predicates.cljd
clj/test/cljd/test_reader/reader_test.cljd
run-tests

- Adds functions to `cljd.core`: `long`, `float`, `float?`, `ex-cause`
- Adds single-arity `cljd.edn/read-string`
- Updates `cljd.test/assert-expr` `thrown-with-msg?` assertion to use `ex-message` instead of `.-message`
- Resolves all type warnings that previously showed up in the test output
These changes were made mostly for the convenience they provide in porting other libraries to ClojureDart.

Add several convenience functions more closely align with those in clojure.core and cljs.core libraries
